-- Phase 2 작업 6: 족보 "안 푼 거 우선" 큐 + 작업 5: 세션 완료 기록
-- Supabase SQL Editor에서 한 번 실행

-- ---------------------------------------------------------------------------
-- 1) answer_logs: ml_features.question_id 기준 조회 인덱스
--    (족보 question_id는 bigint 컬럼이 아닌 ml_features JSON에 문자열로 저장)
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_answer_logs_jogbo_ml_qid
  ON public.answer_logs ((ml_features->>'question_id'), student_id, tag, created_at_kst DESC)
  WHERE quiz_type = 'input';

-- ---------------------------------------------------------------------------
-- 2) RPC: 학생+태그+question_id 목록에 대한 마지막 풀이 시각
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.get_jogbo_question_history(
  p_student_id text,
  p_tag text,
  p_question_ids text[]
)
RETURNS TABLE (
  question_id text,
  last_answered_at timestamptz
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    al.ml_features->>'question_id' AS question_id,
    MAX(al.created_at) AS last_answered_at
  FROM public.answer_logs al
  WHERE al.student_id = p_student_id
    AND al.tag = p_tag
    AND al.quiz_type = 'input'
    AND al.ml_features->>'question_id' IS NOT NULL
    AND al.ml_features->>'question_id' = ANY(p_question_ids)
  GROUP BY al.ml_features->>'question_id';
$$;

GRANT EXECUTE ON FUNCTION public.get_jogbo_question_history(text, text, text[]) TO anon, authenticated;

-- ---------------------------------------------------------------------------
-- 3) jogbo_session_completions (작업 5·7 대비 — 이미 있으면 스킵)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.jogbo_session_completions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL,
  tag text,
  session_id uuid NOT NULL,
  question_count integer NOT NULL DEFAULT 0,
  correct_count integer NOT NULL DEFAULT 0,
  is_full_complete boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_jogbo_session_completions_user_created
  ON public.jogbo_session_completions (user_id, created_at DESC);

ALTER TABLE public.jogbo_session_completions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "jogbo_session_completions allow anon insert" ON public.jogbo_session_completions;
CREATE POLICY "jogbo_session_completions allow anon insert" ON public.jogbo_session_completions
  FOR INSERT TO anon WITH CHECK (true);

DROP POLICY IF EXISTS "jogbo_session_completions allow anon select" ON public.jogbo_session_completions;
CREATE POLICY "jogbo_session_completions allow anon select" ON public.jogbo_session_completions
  FOR SELECT TO anon USING (true);
