-- Phase 2: 족보 누적 오답 관리 (jogbo_wrong_dismissed + get_jogbo_wrong_questions RPC)
-- Supabase SQL Editor에서 한 번 실행

-- ---------------------------------------------------------------------------
-- 1) 학생이 "외웠다"고 명시적으로 제외한 오답
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.jogbo_wrong_dismissed (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL,
  tag text NOT NULL,
  question_id text NOT NULL,
  dismissed_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, tag, question_id)
);

CREATE INDEX IF NOT EXISTS idx_jwd_user_tag ON public.jogbo_wrong_dismissed (user_id, tag);

ALTER TABLE public.jogbo_wrong_dismissed ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "jwd_anon_insert" ON public.jogbo_wrong_dismissed;
CREATE POLICY "jwd_anon_insert" ON public.jogbo_wrong_dismissed
  FOR INSERT TO anon WITH CHECK (true);

DROP POLICY IF EXISTS "jwd_anon_select" ON public.jogbo_wrong_dismissed;
CREATE POLICY "jwd_anon_select" ON public.jogbo_wrong_dismissed
  FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS "jwd_anon_delete" ON public.jogbo_wrong_dismissed;
CREATE POLICY "jwd_anon_delete" ON public.jogbo_wrong_dismissed
  FOR DELETE TO anon USING (true);

-- ---------------------------------------------------------------------------
-- 2) RPC: 태그별 "현재 누적 오답" (최신 풀이 correct=false, dismissed 제외)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.get_jogbo_wrong_questions(
  p_student_id text,
  p_tag text
)
RETURNS TABLE (
  question_id text,
  last_wrong_at timestamptz
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  WITH latest AS (
    SELECT
      al.ml_features->>'question_id' AS qid,
      al.correct,
      al.created_at,
      ROW_NUMBER() OVER (
        PARTITION BY al.ml_features->>'question_id'
        ORDER BY al.created_at DESC
      ) AS rn
    FROM public.answer_logs al
    WHERE al.student_id = p_student_id
      AND al.tag = p_tag
      AND al.quiz_type = 'input'
      AND al.ml_features->>'question_id' IS NOT NULL
      AND TRIM(al.ml_features->>'question_id') <> ''
  )
  SELECT l.qid AS question_id, l.created_at AS last_wrong_at
  FROM latest l
  WHERE l.rn = 1
    AND l.correct = false
    AND NOT EXISTS (
      SELECT 1
      FROM public.jogbo_wrong_dismissed d
      WHERE d.user_id = p_student_id
        AND d.tag = p_tag
        AND d.question_id = l.qid
    )
  ORDER BY l.created_at DESC;
$$;

GRANT EXECUTE ON FUNCTION public.get_jogbo_wrong_questions(text, text) TO anon, authenticated;
